// GENERADO por python-engine/exportar_catalogo.py desde ejercicios_db.py.
// NO editar a mano: cambia ejercicios_db.py y vuelve a correr el script.
export interface EjercicioMotor {
  nombre: string;
  patron: string;
  musculo: string;
  equipo: string;
  bloques: string;
  pref: number;
}

export const CATALOGO_MOTOR: EjercicioMotor[] = [
  {"nombre": "Press de Banca con Barra", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "barra", "bloques": "AB", "pref": 1},
  {"nombre": "Press Inclinado con Mancuernas", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "mancuerna", "bloques": "AB", "pref": 2},
  {"nombre": "Press de Banca con Mancuernas", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "mancuerna", "bloques": "AB", "pref": 3},
  {"nombre": "Press Inclinado con Barra", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "barra", "bloques": "AB", "pref": 4},
  {"nombre": "Fondos en Paralelas", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "peso_corporal", "bloques": "B", "pref": 5},
  {"nombre": "Press Pecho en Maquina", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "maquina", "bloques": "B", "pref": 6},
  {"nombre": "Pec Deck (Aperturas Maquina)", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "maquina", "bloques": "C", "pref": 7},
  {"nombre": "Aperturas con Mancuernas", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "mancuerna", "bloques": "C", "pref": 8},
  {"nombre": "Cruce de Poleas", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "polea", "bloques": "C", "pref": 9},
  {"nombre": "Cruce de Poleas Bajo-Alto", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "polea", "bloques": "C", "pref": 10},
  {"nombre": "Press Inclinado en Maquina", "patron": "empuje_horizontal", "musculo": "pecho", "equipo": "maquina", "bloques": "B", "pref": 11},
  {"nombre": "Press Militar Mancuernas (Sentado)", "patron": "empuje_vertical", "musculo": "hombros", "equipo": "mancuerna", "bloques": "AB", "pref": 1},
  {"nombre": "Press Arnold con Mancuernas", "patron": "empuje_vertical", "musculo": "hombros", "equipo": "mancuerna", "bloques": "AB", "pref": 2},
  {"nombre": "Press Militar con Barra", "patron": "empuje_vertical", "musculo": "hombros", "equipo": "barra", "bloques": "AB", "pref": 3},
  {"nombre": "Press Hombro en Maquina", "patron": "empuje_vertical", "musculo": "hombros", "equipo": "maquina", "bloques": "B", "pref": 4},
  {"nombre": "Remo con Mancuerna a 1 Mano", "patron": "tiron_horizontal", "musculo": "dorsales", "equipo": "mancuerna", "bloques": "AB", "pref": 1},
  {"nombre": "Remo con Barra Agarre Prono", "patron": "tiron_horizontal", "musculo": "dorsales", "equipo": "barra", "bloques": "AB", "pref": 2},
  {"nombre": "Remo en Polea Baja Agarre Neutro", "patron": "tiron_horizontal", "musculo": "dorsales", "equipo": "polea", "bloques": "B", "pref": 3},
  {"nombre": "Remo en Maquina Martillo", "patron": "tiron_horizontal", "musculo": "dorsales", "equipo": "maquina", "bloques": "B", "pref": 4},
  {"nombre": "Remo en Punta (T-Bar)", "patron": "tiron_horizontal", "musculo": "dorsales", "equipo": "barra", "bloques": "B", "pref": 5},
  {"nombre": "Jalon al Pecho Agarre Amplio", "patron": "tiron_vertical", "musculo": "dorsales", "equipo": "polea", "bloques": "AB", "pref": 1},
  {"nombre": "Dominadas", "patron": "tiron_vertical", "musculo": "dorsales", "equipo": "peso_corporal", "bloques": "AB", "pref": 2},
  {"nombre": "Jalon Unilateral en Polea", "patron": "tiron_vertical", "musculo": "dorsales", "equipo": "polea", "bloques": "B", "pref": 3},
  {"nombre": "Jalon Agarre Neutro", "patron": "tiron_vertical", "musculo": "dorsales", "equipo": "polea", "bloques": "B", "pref": 4},
  {"nombre": "Pullover en Polea Alta", "patron": "tiron_vertical", "musculo": "dorsales", "equipo": "polea", "bloques": "C", "pref": 5},
  {"nombre": "Sentadilla Libre con Barra", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "barra", "bloques": "AB", "pref": 1},
  {"nombre": "Prensa de Piernas 45 grados", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "maquina", "bloques": "AB", "pref": 2},
  {"nombre": "Hack Squat (Maquina)", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "maquina", "bloques": "AB", "pref": 3},
  {"nombre": "Sentadilla Frontal con Barra", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "barra", "bloques": "AB", "pref": 4},
  {"nombre": "Sentadilla Bulgara con Mancuernas", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "mancuerna", "bloques": "B", "pref": 5},
  {"nombre": "Zancadas con Mancuernas", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "mancuerna", "bloques": "B", "pref": 6},
  {"nombre": "Sentadilla con Mancuernas (Goblet)", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "mancuerna", "bloques": "B", "pref": 7},
  {"nombre": "Step Up con Mancuernas", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "mancuerna", "bloques": "B", "pref": 8},
  {"nombre": "Extensiones de Cuadriceps (Maquina)", "patron": "dominante_rodilla", "musculo": "cuadriceps", "equipo": "maquina", "bloques": "C", "pref": 9},
  {"nombre": "Hip Thrust con Barra", "patron": "dominante_cadera", "musculo": "gluteos", "equipo": "barra", "bloques": "AB", "pref": 1},
  {"nombre": "Peso Muerto Rumano con Barra", "patron": "dominante_cadera", "musculo": "isquios", "equipo": "barra", "bloques": "AB", "pref": 2},
  {"nombre": "Peso Muerto Rumano con Mancuernas", "patron": "dominante_cadera", "musculo": "isquios", "equipo": "mancuerna", "bloques": "AB", "pref": 3},
  {"nombre": "Peso Muerto Convencional", "patron": "dominante_cadera", "musculo": "isquios", "equipo": "barra", "bloques": "A", "pref": 4},
  {"nombre": "Peso Muerto Sumo con Barra", "patron": "dominante_cadera", "musculo": "gluteos", "equipo": "barra", "bloques": "AB", "pref": 5},
  {"nombre": "Extensiones Lumbares en Maquina", "patron": "dominante_cadera", "musculo": "lumbar", "equipo": "maquina", "bloques": "C", "pref": 6},
  {"nombre": "Hiperextension con Lastre", "patron": "dominante_cadera", "musculo": "lumbar", "equipo": "peso_corporal", "bloques": "C", "pref": 7},
  {"nombre": "Hiperextension Inversa", "patron": "dominante_cadera", "musculo": "lumbar", "equipo": "maquina", "bloques": "C", "pref": 8},
  {"nombre": "Curl de Isquios Sentado (Maquina)", "patron": "aislamiento_isquios", "musculo": "isquios", "equipo": "maquina", "bloques": "C", "pref": 1},
  {"nombre": "Curl de Isquios Tumbado (Maquina)", "patron": "aislamiento_isquios", "musculo": "isquios", "equipo": "maquina", "bloques": "C", "pref": 2},
  {"nombre": "Curl Nordico", "patron": "aislamiento_isquios", "musculo": "isquios", "equipo": "peso_corporal", "bloques": "C", "pref": 3},
  {"nombre": "Elevaciones Laterales Mancuernas", "patron": "aislamiento_hombro", "musculo": "hombros", "equipo": "mancuerna", "bloques": "C", "pref": 1},
  {"nombre": "Elevaciones Laterales Polea Baja", "patron": "aislamiento_hombro", "musculo": "hombros", "equipo": "polea", "bloques": "C", "pref": 2},
  {"nombre": "Elevaciones Laterales en Maquina", "patron": "aislamiento_hombro", "musculo": "hombros", "equipo": "maquina", "bloques": "C", "pref": 3},
  {"nombre": "Face Pull Polea Alta", "patron": "aislamiento_hombro_post", "musculo": "hombros", "equipo": "polea", "bloques": "C", "pref": 1},
  {"nombre": "Pec Deck Invertido", "patron": "aislamiento_hombro_post", "musculo": "hombros", "equipo": "maquina", "bloques": "C", "pref": 2},
  {"nombre": "Pajaros con Mancuernas", "patron": "aislamiento_hombro_post", "musculo": "hombros", "equipo": "mancuerna", "bloques": "C", "pref": 3},
  {"nombre": "Curl Inclinado con Mancuernas", "patron": "aislamiento_biceps", "musculo": "biceps", "equipo": "mancuerna", "bloques": "C", "pref": 1},
  {"nombre": "Curl con Barra EZ", "patron": "aislamiento_biceps", "musculo": "biceps", "equipo": "barra", "bloques": "C", "pref": 2},
  {"nombre": "Curl Predicador con Barra EZ", "patron": "aislamiento_biceps", "musculo": "biceps", "equipo": "barra", "bloques": "C", "pref": 3},
  {"nombre": "Curl Martillo con Mancuernas", "patron": "aislamiento_biceps", "musculo": "biceps", "equipo": "mancuerna", "bloques": "C", "pref": 4},
  {"nombre": "Curl con Mancuernas", "patron": "aislamiento_biceps", "musculo": "biceps", "equipo": "mancuerna", "bloques": "C", "pref": 5},
  {"nombre": "Curl Polea Baja Cuerda", "patron": "aislamiento_biceps", "musculo": "biceps", "equipo": "polea", "bloques": "C", "pref": 6},
  {"nombre": "Curl Concentrado", "patron": "aislamiento_biceps", "musculo": "biceps", "equipo": "mancuerna", "bloques": "C", "pref": 7},
  {"nombre": "Extension Triceps sobre Cabeza", "patron": "aislamiento_triceps", "musculo": "triceps", "equipo": "mancuerna", "bloques": "C", "pref": 1},
  {"nombre": "Press Frances con Barra EZ", "patron": "aislamiento_triceps", "musculo": "triceps", "equipo": "barra", "bloques": "C", "pref": 2},
  {"nombre": "Extension Triceps Polea Cuerda", "patron": "aislamiento_triceps", "musculo": "triceps", "equipo": "polea", "bloques": "C", "pref": 3},
  {"nombre": "Extension Triceps Polea Barra", "patron": "aislamiento_triceps", "musculo": "triceps", "equipo": "polea", "bloques": "C", "pref": 4},
  {"nombre": "Press Cerrado con Barra", "patron": "aislamiento_triceps", "musculo": "triceps", "equipo": "barra", "bloques": "C", "pref": 5},
  {"nombre": "Fondos en Banco", "patron": "aislamiento_triceps", "musculo": "triceps", "equipo": "peso_corporal", "bloques": "C", "pref": 6},
  {"nombre": "Abduccion de Cadera en Maquina", "patron": "aislamiento_abductor", "musculo": "gluteos", "equipo": "maquina", "bloques": "C", "pref": 1},
  {"nombre": "Abduccion de Cadera en Polea", "patron": "aislamiento_abductor", "musculo": "gluteos", "equipo": "polea", "bloques": "C", "pref": 2},
  {"nombre": "Caminata Lateral con Banda", "patron": "aislamiento_abductor", "musculo": "gluteos", "equipo": "peso_corporal", "bloques": "C", "pref": 3},
  {"nombre": "Aduccion de Cadera en Maquina", "patron": "aislamiento_aductor", "musculo": "aductores", "equipo": "maquina", "bloques": "C", "pref": 1},
  {"nombre": "Sentadilla Sumo con Mancuerna", "patron": "aislamiento_aductor", "musculo": "aductores", "equipo": "mancuerna", "bloques": "C", "pref": 2},
  {"nombre": "Zancada Lateral con Mancuerna", "patron": "aislamiento_aductor", "musculo": "aductores", "equipo": "mancuerna", "bloques": "C", "pref": 3},
  {"nombre": "Patada de Gluteo en Polea", "patron": "aislamiento_gluteo", "musculo": "gluteos", "equipo": "polea", "bloques": "C", "pref": 1},
  {"nombre": "Patada de Gluteo en Maquina", "patron": "aislamiento_gluteo", "musculo": "gluteos", "equipo": "maquina", "bloques": "C", "pref": 2},
  {"nombre": "Puente de Gluteo a 1 Pierna", "patron": "aislamiento_gluteo", "musculo": "gluteos", "equipo": "peso_corporal", "bloques": "C", "pref": 3},
  {"nombre": "Rotacion Externa en Polea", "patron": "rotadores", "musculo": "hombros", "equipo": "polea", "bloques": "C", "pref": 1},
  {"nombre": "Rotacion Externa con Mancuerna", "patron": "rotadores", "musculo": "hombros", "equipo": "mancuerna", "bloques": "C", "pref": 2},
  {"nombre": "Cubanos con Mancuernas", "patron": "rotadores", "musculo": "hombros", "equipo": "mancuerna", "bloques": "C", "pref": 3},
  {"nombre": "Encogimientos con Mancuernas", "patron": "trapecio", "musculo": "trapecios", "equipo": "mancuerna", "bloques": "C", "pref": 1},
  {"nombre": "Encogimientos con Barra", "patron": "trapecio", "musculo": "trapecios", "equipo": "barra", "bloques": "C", "pref": 2},
  {"nombre": "Encogimientos en Polea", "patron": "trapecio", "musculo": "trapecios", "equipo": "polea", "bloques": "C", "pref": 3},
  {"nombre": "Elevaciones de Pantorrilla De Pie", "patron": "pantorrilla", "musculo": "gemelos", "equipo": "maquina", "bloques": "C", "pref": 1},
  {"nombre": "Elevaciones de Pantorrilla Sentado", "patron": "pantorrilla", "musculo": "gemelos", "equipo": "maquina", "bloques": "C", "pref": 2},
  {"nombre": "Elevacion de Pantorrilla en Prensa", "patron": "pantorrilla", "musculo": "gemelos", "equipo": "maquina", "bloques": "C", "pref": 3},
  {"nombre": "Curl Invertido con Barra EZ", "patron": "antebrazo", "musculo": "antebrazos", "equipo": "barra", "bloques": "C", "pref": 1},
  {"nombre": "Farmer's Carry", "patron": "antebrazo", "musculo": "antebrazos", "equipo": "mancuerna", "bloques": "C", "pref": 2},
  {"nombre": "Curl de Muneca con Barra (Flexores)", "patron": "antebrazo", "musculo": "antebrazos", "equipo": "barra", "bloques": "C", "pref": 3},
  {"nombre": "Curl de Muneca Inverso (Extensores)", "patron": "antebrazo", "musculo": "antebrazos", "equipo": "barra", "bloques": "C", "pref": 4},
  {"nombre": "Pinzamiento de Disco", "patron": "antebrazo", "musculo": "antebrazos", "equipo": "peso_corporal", "bloques": "C", "pref": 5},
  {"nombre": "Rodillo de Muneca (Wrist Roller)", "patron": "antebrazo", "musculo": "antebrazos", "equipo": "peso_corporal", "bloques": "C", "pref": 6},
  {"nombre": "Curl Zottman con Mancuernas", "patron": "antebrazo", "musculo": "antebrazos", "equipo": "mancuerna", "bloques": "C", "pref": 7},
  {"nombre": "Extension de Muneca con Banda", "patron": "antebrazo", "musculo": "antebrazos", "equipo": "peso_corporal", "bloques": "C", "pref": 8},
  {"nombre": "Plancha Frontal", "patron": "core", "musculo": "abdomen", "equipo": "peso_corporal", "bloques": "C", "pref": 1},
  {"nombre": "Elevaciones de Piernas Colgado", "patron": "core", "musculo": "abdomen", "equipo": "peso_corporal", "bloques": "C", "pref": 2},
  {"nombre": "Crunch en Polea Alta", "patron": "core", "musculo": "abdomen", "equipo": "polea", "bloques": "C", "pref": 3},
  {"nombre": "Rueda Abdominal", "patron": "core", "musculo": "abdomen", "equipo": "peso_corporal", "bloques": "C", "pref": 4},
  {"nombre": "Pallof Press en Polea", "patron": "core", "musculo": "abdomen", "equipo": "polea", "bloques": "C", "pref": 5},
  {"nombre": "Eliptica", "patron": "cardio", "musculo": "abdomen", "equipo": "maquina", "bloques": "C", "pref": 1},
  {"nombre": "Bicicleta Estatica", "patron": "cardio", "musculo": "abdomen", "equipo": "maquina", "bloques": "C", "pref": 2},
  {"nombre": "Caminata Inclinada", "patron": "cardio", "musculo": "abdomen", "equipo": "maquina", "bloques": "C", "pref": 3}
];
